// categories
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';

// commentCreate
export const COMMENT_CREATE_SUBMITTING = 'COMMENT_CREATE_SUBMITTING';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_CREATE_ERROR = 'COMMENT_CREATE_ERROR';
export const COMMENT_CREATE_RESET = 'COMMENT_CREATE_RESET';
export const COMMENT_CREATE_SET_TEXT = 'COMMENT_CREATE_SET_TEXT';

// comments
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';
export const RESET_COMMENTS = 'RESET_COMMENTS';

// post
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const RESET_POST = 'RESET_POST';

// postCreate
export const POST_CREATE_SUBMITTING = 'POST_CREATE_SUBMITTING';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_ERROR = 'POST_CREATE_ERROR';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';
export const POST_CREATE_SET_TEXT = 'POST_CREATE_SET_TEXT';
export const POST_CREATE_SET_CATEGORY = 'POST_CREATE_SET_CATEGORY';

// posts
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const RESET_POSTS = 'RESET_POSTS';
